// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Microservice.Models;

public partial class Course
{
    public string IdCourse { get; set; }

    public string CourseName { get; set; }

    public int UserId { get; set; }
}