// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Microservice.Models;

public partial class Roles
{
    public string RoleId { get; set; }

    public string RoleName { get; set; }

    public int IdUser { get; set; }

    public virtual User IdUserNavigation { get; set; }
}